name: Dart CI

on: push
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

env:
  flutter_channel: 'stable' # or: 'dev' or 'beta'
  flutter_version: '2.2.2'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: subosito/flutter-action@v1
      with:
        channel: ${{ env.flutter_channel }}
        flutter-version: ${{ env.flutter_version }}

    - uses: actions/setup-java@v1
      with:
        java-version: '8'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: build APK
      working-directory: ./
      shell: bash
      run: |
        rm -rf build || true
        rm -rf .idea || true
        rm -rf .vscode || true
        rm -rf *.lock || true
        flutter clean
        flutter pub get
        flutter build apk --split-per-abi

    - name: artifact app-armeabi-v7a-release
      uses: actions/upload-artifact@v2
      with:
        name: apk_app-armeabi-v7a-release
        path: ./build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk

    - name: artifact app-arm64-v8a-release
      uses: actions/upload-artifact@v2
      with:
        name: apk_app-arm64-v8a-release
        path: ./build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
        
